### ISSUE TITLE
Is it possible one core used as server and client at same time? 

### ISSUE THREAD

**Issue by swordligit** [NXPmicro/rpmsg-lite#18]
I have two cores(call them A and B), using rpmsg-lite to communicate between them,  core A
has some peripheral(like UART) and core B mainly as DSP.
When playing audio, IMO, core A used as client, and core B severed  as  server, but when printing
trace, the role is changed, A as Server and B as client?  So the A(or B) used as server
and client at same time,  is it possible? please give some advice.
Thanks a lot.

**Comment by Hadatko** [comment]
Hi @swordligit , eRPC is using rpmsg-lite also for bidirectional communication.

**Comment by swordligit** [comment]
Thank you @Hadatko , will check the eRPC and run the examples.

**Comment by Hadatko** [comment]
What i wanted to say is that you can use it bidirectionaly. You are welcome. 
I don't see any example mentioned here. But if you would like to get rid of eRPC layer you can download simple rpmsg demo from NXP webpage directly https://mcuxpresso.nxp.com/en/welcome
You can choose board based on rpmsg-lite port file. Based on port files you know supported boards.

**Comment by MichalPrincNXP** [comment]
Thanks, @Hadatko , and the link to the erpc project on Github is here:
https://github.com/EmbeddedRPC/erpc

**Comment by swordligit** [comment]
Thanks @Hadatko  @MichalPrincNXP, I know the RPMSG support bidirection, and I will not pass through the eRPC,
my requirement is one core support client and server at same time.

**Comment by swordligit** [comment]
Oh, found an issue in eRPC site,
https://github.com/EmbeddedRPC/erpc/issues/80
It is still open, but anyway will try to dig it.
