### ISSUE TITLE
rpmsg_lite_is_link_up return value

### ISSUE THREAD

**Issue by Hadatko** [NXPmicro/rpmsg-lite#22]
![image](https://user-images.githubusercontent.com/13130700/146931230-da17d377-534d-46b4-bb7d-bcfad09dca0e.png)

Hi @MichalPrincNXP , isn't better to change return value type to uint32_t of function instead of retyping link_state?

**Comment by MichalPrincNXP** [comment]
Thanks for pointing at, yes, it would be better. Will update.

**Comment by MichalPrincNXP** [comment]
Implemented internally, will provide publicly with other changes soon.
