### ISSUE TITLE
Can rpmsg lite work well as master and remote at the same time?

### ISSUE THREAD

**Issue by zhangjk2752** [NXPmicro/rpmsg-lite#28]
On my board, there are three cores. 1 APU and 2 R52s.  Then APU works as a master to communicate with R52 A,  also R52 A should actively send some message to R52 B. So for R52 A, it should run both rpmsg_lite_master_init and rpmsg_lite_remote_init. I want to know if the rpmsg-lite code can support the use like this? someone's share may help me a lot , tks.

**Comment by MichalPrincNXP** [comment]
Hello @zhangjk2752 
you have to create two rpmsg_lite instances on the R52 A, each having own shared memory and link_id. It is not possible to use just one rpmsg_lite instance in case of R52 A that is intended to be both the master and remote.

**Comment by zhangjk2752** [comment]
Ok, get it.  Tks.
