### ISSUE TITLE
Request for various sample apps like OpenAMP

### ISSUE THREAD

**Issue by MHesham** [NXPmicro/rpmsg-lite#4]
Was looking in the rpmsg-lite documentation for reference to something similar to https://github.com/OpenAMP/open-amp/tree/master/apps that demonstrates the framework usage end-to-end. Something I can build on.
The only thing I could find close is https://github.com/EmbeddedRPC/erpc-imx-demos but it doesn't show how to use rpmsg-lite in a Master, and it is only 1 sample.

**Comment by MarekNovakNXP** [comment]
Hi MHesham,

Additional examples can be found here: https://community.nxp.com/docs/DOC-334083 
Basically, you can download the MCUXpresso and in the code base, you would search for multicore examples.

What is the hardware you would like to use?

Regards,
Marek

**Comment by MHesham** [comment]
Thanks Marek for the reference. I am using iMX7D Sabre, and I am interested in a master side initialization sequence in C.

**Comment by mhanuel26** [comment]
Hello @MarekNovakNXP,

Is there an example of bare metal rpmsg-lite ? The rpmsg_queue depends on FreeRTOS, I know queues depend on rtos but how can I use the rpmsg-lite with bm only?

Please let me know,

**Comment by Hadatko** [comment]
Hi @mhanuel26  of course there are also bm examples (but likely only for kinetis board like: LPCXpresso54114). But you can get inspiration there.
